### ISSUE TITLE
[JSON] Invalid JSON value! 4

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Next21Team/Slot-Machine#1]
При попытке сохранить установленный автомат:
```
L 02/18/2022 - 14:47:41: [JSON] Invalid JSON value! 4
L 02/18/2022 - 14:47:41: [AMXX] Displaying debug trace (plugin "next21_slot_machine.amxx", version "0.1")
L 02/18/2022 - 14:47:41: [AMXX] Run time error 10: native error (native "json_object_set_value")
L 02/18/2022 - 14:47:41: [AMXX]    [0] next21_slot_machine.sma::save_machines (line 455)
L 02/18/2022 - 14:47:41: [AMXX]    [1] next21_slot_machine.sma::machine_menu_handler (line 140)
```

**Comment by Nord1cWarr1or** [comment]
@Psycrow101 из того кода для меня не совсем ясно, из-за чего возникает ошибка. В плагине же вроде всё правильно.
И ещё не пойму, она то возникает, то нет. Какая-то фигня. Можете объяснить?

**Comment by Psycrow101** [comment]
@Nord1cWarr1or https://github.com/alliedmodders/amxmodx/commit/363871a860d4550d71299130a8409f7e32d754e3 в модуле JSON указывался Handle_Object вместо Handle_Value. Думаю из-за этого вызывалось исключение, так как после данного фикса ошибка не проявлялась.

**Comment by Nord1cWarr1or** [comment]
> @Nord1cWarr1or [alliedmodders/amxmodx@363871a](https://github.com/alliedmodders/amxmodx/commit/363871a860d4550d71299130a8409f7e32d754e3) в модуле JSON указывался Handle_Object вместо Handle_Value. Думаю из-за этого вызывалось исключение, так как после данного фикса ошибка не проявлялась.

спасибо. Обновил АМХХ, ошибки нет.
