### ISSUE TITLE
Wrong hitbox size after compiling model

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Next21Team/Slot-Machine#2]
После смены текстур через python-скрипт и компиляции через studiomdl по инструкции, в папке dist, модель почему-то имеет следующий размер хитбокса: `-539.840027 0.000000 -321.279999 539.840027 2397.760010 616.960022`.

Кроме замены чисел в файле `text.json` никаких манипуляций не производилось. 

Компилятор [от Дяди Миши](https://hlfx.ru/forum/showthread.php?s=&threadid=5237).

**Comment by Psycrow101** [comment]
Похоже в этой версии компилятора хитбокс масштабируется вместе с геометрией. Исправил для совместимости.
