### ISSUE TITLE
the prise does not work diagonally

### ISSUE THREAD

**Issue by Nord1cWarr1or** [Next21Team/Slot-Machine#4]
If diagonal is from up to down - then everything is ok.
but if diagonal is from down to up - it not works. Why?
![20220318225012_1](https://user-images.githubusercontent.com/47604048/159137509-54046b3f-3868-4628-8417-51ec100e8e7e.jpg)
![20220319232823_1](https://user-images.githubusercontent.com/47604048/159137512-c65f930b-fc8a-4f1a-bce0-821ea23da2fa.jpg)

**Comment by Psycrow101** [comment]
I thought according to the rules only the main diagonal is counted, but now I see that this is not an obvious behavior. Updated.

**Comment by Nord1cWarr1or** [comment]
Verified
